imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %assets_version_param%
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"

    strict_variables: "%kernel.debug%"

    form:
#        resources: ['bootstrap_3_layout.html.twig']
        resources: ['bootstrap_3_horizontal_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - AwFrontendTemplateBundle
        - AwBackendTemplateBundle
    filters:
        cssrewrite: ~

    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"


    assets:
#bootstrap
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.min.js
        bootstrap_js_ie:
            inputs:
                - %kernel.root_dir%/../vendor/afarkas/html5shiv/dist/html5shiv.min.js
                - %kernel.root_dir%/../vendor/rogeriopradoj/respond/dest/respond.min.js

        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.min.css
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap-theme.css
            filters: [cssrewrite]

        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"
#ionicons
        ionicons_css:
            inputs:
                - %kernel.root_dir%/../vendor/driftyco/ionicons/css/ionicons.min.css

        ionicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/driftyco/ionicons/fonts/ionicons.ttf
            output: "fonts/ionicons.ttf"

        ionicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/driftyco/ionicons/fonts/ionicons.woff
            output: "fonts/ionicons.woff"

#font-awesome
        font_awesome_css:
            inputs:
                - %kernel.root_dir%/../vendor/fortawesome/font-awesome/css/font-awesome.min.css
            filters: [cssrewrite]

        fontawesome_otf:
            inputs:
                - %kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/FontAwesome.otf
            output: "fonts/FontAwesome.otf"
        fontawesome_eot:
            inputs:
                - %kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.eot
            output: "fonts/fontawesome-webfont.eot"
        fontawesome_svg:
            inputs:
                - %kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.svg
            output: "fonts/fontawesome-webfont.svg"
        fontawesome_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.ttf
            output: "fonts/fontawesome-webfont.ttf"
        fontawesome_woff:
            inputs:
                - %kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.woff
            output: "fonts/fontawesome-webfont.woff"
        fontawesome_woff2:
            inputs:
                - %kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.woff2
            output: "fonts/fontawesome-webfont.woff2"

#jquery
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.min.js

#angular
        angularjs:
            inputs:
                - %kernel.root_dir%/../bower_components/angular/angular.min.js




# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Aw\UserBundle\Entity\User
