frontend:
    resource: "@AppBundle/Resources/config/routing/frontend/index.yml"
    prefix: /

frontend_minicart:
    resource: "@AppBundle/Resources/config/routing/frontend/minicart.yml"
    prefix: /cart