AppBundle\Entity\Corderdomain:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    domain:
      type: string
      nullable: true
    price:
      type: decimal
      precision: 2
    executed:
      type: boolean
      nullable: true
  oneToOne:
    corder:
      targetEntity: Corder
      inversedBy: corderdomain
      joinColumn:
        corder_id:
          referencedColumnName: id
          nullable: false
  manyToOne:
    domainproduct:
      targetEntity: Domainproduct
      inversedBy: corderdomain
      joinColumns:
        domainproduct_id:
          referencedColumnName: id
          nullable: false
