AppBundle\Entity\Dnsdefault:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    dns:
      type: string
      length: 255
      nullable: false