AppBundle\Entity\Domaincontacttype:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: false
  oneToMany:
    domaincontact:
      targetEntity: Domaincontact
      mappedBy: domaincontactype