AppBundle\Entity\Domainprovider:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    nameprovider:
      type: string
      nullable: true
    module:
      type: string
      nullable: true
    api:
      type: boolean
      nullable: true
  oneToMany:
    tld:
      targetEntity: Tld
      mappedBy: domainprovider
