AppBundle\Entity\Paymentmethod:
  type: entity
  repositoryClass: AppBundle\Entity\PaymentmethodRepository
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: true
    path:
      type: string
      nullable: false
    alias:
      type: string
      nullable: true
    enable:
      type: boolean
      nullable: false
  oneToMany:
    payment:
      targetEntity: Payment
      mappedBy: paymentmethod
