AppBundle\Entity\Paymentstatus:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    status:
      type: string
      nullable: true
  oneToMany:
    payment:
      targetEntity: Payment
      mappedBy: paymentstatus
