AppBundle\Entity\Product:
  type: entity
  table: product
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
      nullable: false
  oneToMany:
    hostingproduct:
      targetEntity: Hostingproduct
      mappedBy: product
    domainproduct:
      targetEntity: Domainproduct
      mappedBy: product