AppBundle\Entity\Resellerclubuser:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    code:
      type: string
      nullable: true
  oneToOne:
    user:
      targetEntity: Aw\UserBundle\Entity\User
      inversedBy: resellerclubuser
      joinColumn:
        name: user_id
        referencedColumnName: id
