AppBundle\Entity\Serverhosting:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    username:
      type: string
      length: 255
      nullable: false
    password:
      type: string
      length: 255
      nullable: false
    hostingplan:
      type: string
      length: 255
      nullable: false
